language: node_js

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '9'
  - '8'
  - '6'

install: yarn install --ignore-engines

script: yarn run build

after_success:
  - yarn run travis-deploy-once "yarn run semantic-release && yarn run docs"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
