language: node_js

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '9'
  - '8'
  - '6'

install: yarn install --ignore-engines

script: 
  - yarn run build
  - yarn run build:docs

after_success:
  - yarn run travis-deploy-once "yarn run semantic-release"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: storybook-static
  on:
    branch: master

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
